import type { PageTurnBookMedia } from "@ethical-tech/pageturn-book";

export type V3PublicationMedia = PageTurnBookMedia;

const ethicalAiMedia: V3PublicationMedia = {
  defaultTreatment: "popout",
  figures: [
    {
      id: "ai-ethics-frameworks",
      chapterId: "responsible-ai",
      afterAnchor:
        "list-ieee-ethically-aligned-design-the-engineering-pr-41441af64f",
      src: "../media/what-is-ethical-ai/ai-ethics-frameworks.webp",
      width: 1656,
      height: 1418,
      alt: "Circular diagram of ten landmark resources for building an AI ethics framework, including IEEE, EU, Montreal, Asilomar, Partnership on AI, OECD, Toronto, AI Now, FAT/ML, and Berkman Klein resources.",
      caption:
        "Figure 4. Ten landmark resources for building an AI ethics framework.",
    },
    {
      id: "colab-portfolio-maturity",
      chapterId: "colab",
      afterAnchor:
        "p-each-project-is-best-understood-through-three-le-e0fb4bfc09",
      src: "../media/what-is-ethical-ai/colab-portfolio-maturity.webp",
      width: 1778,
      height: 895,
      alt: "Horizontal bar chart showing the July 2026 maturity of ten Ethical Tech CoLab projects, from proposed through built and validated.",
      caption:
        "Figure 1. Maturity of the Ethical Tech CoLab portfolio, July 2026.",
    },
    {
      id: "colab-five-pillars",
      chapterId: "colab",
      afterAnchor:
        "list-ethics-before-algorithms-the-colab-treats-the-cu-6e7ce168d6",
      src: "../media/what-is-ethical-ai/colab-five-pillars.webp",
      width: 1791,
      height: 1008,
      alt: "Diagram of five pillars for legitimate humanitarian AI: humanity and do no harm, data minimization and privacy, real consent or none, transparency and honest uncertainty, and accountability and local governance, resting on international human rights law and humanitarian principles.",
      caption:
        "Figure 4. The five pillars of ethics of the Ethical Tech CoLab.",
    },
  ],
};

const pluralityRevision =
  "86158859464aee75633acd854c656928121a7fd8";
const pluralityFigureRoot =
  `https://raw.githubusercontent.com/pluralitybook/plurality/` +
  `${pluralityRevision}/figs/`;

const pluralityMedia: V3PublicationMedia = {
  defaultTreatment: "popout",
  figures: [
    {
      id: "plurality-2-2-b-polis",
      chapterId: "2-2",
      replaceAnchors: [
        "p-figure-diagram-of-an-opinion-displayed-by-polis-c552ade6ad",
        "p-figure-2-2-b-clusters-of-consensual-opinions-gen-5047b3045a",
      ],
      src: `${pluralityFigureRoot}vtaiwan-polis-ai.png`,
      width: 824,
      height: 829,
      alt: "Diagram of an opinion displayed by Polis on vTaiwan, with similar views clustered.",
      caption:
        "Figure 2-2-B. Clusters of consensual opinions generated by Polis on vTaiwan. Source: vTaiwan.tw, CC0.",
    },
    {
      id: "plurality-3-1-a-mandelbrot",
      chapterId: "3-1",
      replaceAnchors: [
        "p-figure-pictures-the-mandelbrot-set-a-canonical-c-bf09dcb6ba",
        "p-figure-3-1-a-the-mandelbrot-set-characterizing-t-642e9438e7",
      ],
      src: `${pluralityFigureRoot}science.jpg`,
      width: 1102,
      height: 434,
      alt: "The Mandelbrot set, a circular snowflake-shaped fractal, shown at two scales.",
      caption:
        "Figure 3-1-A. The Mandelbrot Set. Source: Wikipedia, CC BY-SA 3.0.",
    },
    {
      id: "plurality-3-2-b-georg-simmel",
      chapterId: "3-2",
      replaceAnchors: [
        "p-figure-georg-simmel-with-glasses-and-full-facial-62e20edfdb",
        "p-figure-3-2-b-georg-simmel-source-wikipedia-publi-e14bac2f72",
      ],
      src: `${pluralityFigureRoot}3-2-georg.jpg`,
      width: 552,
      height: 800,
      alt: "Portrait of sociologist Georg Simmel wearing glasses and facial hair.",
      caption:
        "Figure 3-2-B. Georg Simmel. Source: Wikipedia, public domain.",
    },
    {
      id: "plurality-3-3-a-arpanet",
      chapterId: "3-3",
      replaceAnchors: [
        "p-figure-the-decentralized-logical-structure-of-ea-fc075a5910",
        "p-figure-3-3-a-early-logical-structure-of-arpanet-90b455dba8",
      ],
      src: `${pluralityFigureRoot}3-3-arpanet.png`,
      width: 1000,
      height: 716,
      alt: "Diagram of the decentralized logical structure of early ARPANET.",
      caption:
        "Figure 3-3-A. Early logical structure of ARPANET. Source: Wikipedia, public domain.",
    },
    {
      id: "plurality-3-3-c-ted-nelson",
      chapterId: "3-3",
      replaceAnchors: [
        "p-figure-ted-nelson-at-keio-university-japan-1999-8943f02063",
        "p-figure-3-3-c-ted-nelson-at-keio-university-japan-9fc162e706",
      ],
      src: `${pluralityFigureRoot}3-3-TedNelson.jpeg`,
      width: 640,
      height: 480,
      alt: "Ted Nelson at Keio University in Japan in 1999.",
      caption:
        "Figure 3-3-C. Ted Nelson at Keio University, Japan, 1999. Source: Wikipedia, CC BY-SA 4.0.",
    },
    {
      id: "plurality-4-0-a-macintosh",
      chapterId: "4-0",
      replaceAnchors: [
        "p-figure-apple-lisa-ii-macintosh-xl-one-of-the-fir-d53805cca9",
        "p-figure-4-0-a-apple-lisa-ii-macintosh-xl-one-of-t-d3da31c167",
      ],
      src: `${pluralityFigureRoot}4-0-macintosh.jpeg`,
      width: 2592,
      height: 1944,
      alt: "Apple Lisa II Macintosh XL personal computer with a graphical user interface.",
      caption:
        "Figure 4-0-A. Apple Lisa II Macintosh XL. Source: Gerhard Walter via Wikipedia, CC0.",
    },
    {
      id: "plurality-4-3-a-bitcoin",
      chapterId: "4-3",
      replaceAnchors: [
        "p-figure-simple-user-interface-for-use-of-early-bi-051a4faa88",
        "p-figure-4-3-a-an-early-implementation-of-bitcoin-9f572853cc",
      ],
      src: `${pluralityFigureRoot}4-3-bitcoin.png`,
      width: 882,
      height: 556,
      alt: "Early Bitcoin software interface showing wallet and transaction controls.",
      caption:
        "Figure 4-3-A. An early implementation of Bitcoin. Source: Wikipedia, public domain.",
    },
    {
      id: "plurality-5-2-a-mediated-reality",
      chapterId: "5-2",
      replaceAnchors: [
        "p-figure-venn-diagram-with-four-overlapping-circle-b2f806875f",
        "p-figure-5-2-a-mediated-reality-framework-adapted-220cd94f48",
      ],
      src: `${pluralityFigureRoot}mediatedreality.png`,
      width: 537,
      height: 516,
      alt: "Venn diagram of the mediated reality framework with four overlapping circles.",
      caption:
        "Figure 5-2-A. Mediated Reality Framework. Source: Wikipedia, CC BY-SA 3.0.",
    },
    {
      id: "plurality-6-0-c-square-root-scale",
      chapterId: "6-0",
      replaceAnchors: [
        "p-figure-bubbles-filled-with-smaller-bubbles-some-810380cbfd",
        "p-figure-6-0-c-illustration-of-the-square-root-sca-daef2fb1e7",
      ],
      src: `${pluralityFigureRoot}squarerootscale.png`,
      width: 835,
      height: 792,
      alt: "Bubbles containing smaller bubbles and public-domain icons for workplace, media, health, and environment.",
      caption:
        "Figure 6-0-C. The square-root scale of social change. Generated by the authors with public-domain icons.",
    },
    {
      id: "plurality-6-1-a-apple-campus",
      chapterId: "6-1",
      replaceAnchors: [
        "p-figure-apple-155d877846",
        "p-figure-6-1-a-apple-s-famously-unusually-shaped-c-e63ad7c51c",
      ],
      src: `${pluralityFigureRoot}apple.jpg`,
      width: 4056,
      height: 2280,
      alt: "Aerial view of Apple's circular corporate campus.",
      caption:
        "Figure 6-1-A. Apple's unusually shaped corporate campus. Source: Unsplash, free for commercial use.",
    },
    {
      id: "plurality-7-0-a-policy-model",
      chapterId: "7-0",
      replaceAnchors: [
        "p-figure-figure-shows-reshaped-flags-of-the-people-048b72ec2b",
        "p-figure-7-0-a-an-illustration-of-how-the-taiwan-p-b2ac5649ae",
      ],
      src: `${pluralityFigureRoot}Taiwanpolicymodel.png`,
      width: 1920,
      height: 1080,
      alt: "Diagram showing Taiwan's policy model emerging from intersecting PRC, United States, and European Union alternatives.",
      caption:
        "Figure 7-0-A. Taiwan policy model. Generated by the authors with Noun Project icons licensed CC BY 3.0.",
    },
  ],
};

export function publicationMedia(
  bookId: string,
): V3PublicationMedia | undefined {
  return bookId === "what-is-ethical-ai"
    ? ethicalAiMedia
    : bookId === "plurality"
      ? pluralityMedia
      : undefined;
}
